### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by ladas-larry** [lucholaf/react-native-grid-view#6]
Would be great to have an example with fully working infinite scroll.

**Comment by swennemans** [comment]
I agree. I would expect that the same lifecycle method as `<ListView/>` but on first try doesn't seem to work. Anything special that needs to be done?

**Comment by swennemans** [comment]
Forget my last comment it was another issue causing that problem. 

@Dharmoslap here is a simple gist with an infinite scroll list, hopefully this is your use case: https://gist.github.com/swennemans/6bb83bd726fa81c3b547

You can use `onEndReached` to load additional data.

**Comment by ladas-larry** [comment]
thanks!
